### ISSUE TITLE
Propagate font sizes to ZedGraph axis

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/gui#30] opened 2024-11-07 23:30 UTC
There is currently no way to propagate the font information from a TableLayoutPanel to child ZedGraph plots. This is especially important when trying to scale small plots in large TableLayoutPanels.

**Comment by glopesdev** [comment] 2024-11-07 23:31
Duplicate of #24

**Closed by glopesdev** 2024-11-07 23:31 UTC
